[package]
name = "vulkan-tutorial-rust-ash"
version = "0.0.1"
authors = ["odanek <ondrej.danek@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
ash = "0.31.0"
ash-window = "0.5.0"
winit = "0.24.0"